import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/Navbar";
import TabBarBottom from "@/components/TabbarBottom";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
   <body className="min-h-screen bg-white">
        <NavBar />
        <div className="pb-20 sm:pb-0">
          {children}
        </div>
        <TabBarBottom />
      </body>
    </html>
  );
}
